/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './pages/__root';
import { Route as SettingsImport } from './pages/settings';
import { Route as IndexImport } from './pages/index';
import { Route as FavoritesImport } from './pages/favorites';
import { Route as AboutImport } from './pages/about';
import { Route as ToolIdImport } from './pages/$toolId';

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const FavoritesRoute = FavoritesImport.update({
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any);

const ToolIdRoute = ToolIdImport.update({
  path: '/$toolId',
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/favorites': {
      id: '/favorites';
      path: '/favorites';
      fullPath: '/favorites';
      preLoaderRoute: typeof FavoritesImport;
      parentRoute: typeof rootRoute;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    '/$toolId': {
      id: '/$toolId';
      path: '/$toolId';
      fullPath: '/$toolId';
      preLoaderRoute: typeof ToolIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FavoritesRoute,
  SettingsRoute,
  AboutRoute,
  ToolIdRoute,
});

/* prettier-ignore-end */
